# Generated by Django 4.0.1 on 2022-01-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_name'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='country',
        ),
        migrations.AddField(
            model_name='operator',
            name='country',
            field=models.ManyToManyField(to='countries.Country'),
        ),
    ]
